### ISSUE TITLE
[Plan] 231228 - 프로젝트 아이디어 구체화

### ISSUE THREAD

**Issue by robert-min** [FLYAI4/project-plan#2]
### 🎈 Goal
<p>$\tiny{회의를\ 통해 얻고자하는\ 구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- 아이디어 구체화
  - 좋은 서비스(평가를 잘 받을 수 있는 서비스)는 좋은 문제(사람-문제)를 잘 정의하는 과정이 필수
  - 사전 과제를 통해 모은 프로젝트 아이디어를 하나씩 확인하면서 마인드맵 등을을 활용하여 구체화
  - 여러 아이디어 중 우선순위를 설정하여 아이디어 및 기술 검증을 진행
  - 검증 단계를 최대한 짧은 주기로 진행하여 최종 아이디어 선정

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] 회의 전 사전 공지 📅 2023-12-28
  - [x] 회의 목표 및 진행 과정 설명
  - [x] 관심있는 주제 수요 조사(6시 회의 전까지 진행)
- [x] 아아디어 구체화 📅 2023-12-28
  - [x] 마인드맵 사전 준비
  - [x] 회의 진행(당일 회의 시간 부족 시 추가 회의 진행)
  - [x] 우선 순위 결정
- [x] 회의 마무리
  - [x] 회의 내용 정리
  - [x] 아이디어 및 기술 검증을 위한 리서치 가이드 작성 @chanyoungP 

------

**Comment by robert-min** [comment]
## 관심있는 주제 수요 조사

- 가능한 #1 에 모은 모든 아이디어를 구체화할 예정이지만, 회의 진행 시 집중력을 고려하여 사전에 관심있는 주제를 투표하여 관심도가 높은 주제부터 회의 때, 구체화할 예정입니다.
  - 여러 주제 중 내가 관심있는 주제를 최소 2개 ~ 최대 3개까지 선정하여 아래와 같이 눈모양 이모티콘을 표시
  - 관심도가 높은 주제부터 순서대로 아이디에이션을 진행

![스크린샷 2023-12-28 오전 9 46 07](https://github.com/FLYAI4/project-plan/assets/91866763/f73ae144-ca11-417f-b081-ed37833aa549)
▲ 눈모양 이모티콘으로 표시

**Comment by robert-min** [comment]
## 아이디에이션 가이드
- 마인드맵 작성
  1. 구체적인 문제 정의 
  2. 문제 대상(페르소나)
  3. 해결 방법(이 방법이 실제 문제를 해결하는지 확인)
  4. 방법을 구현하기 위한 도구(기술, 기획)

**Comment by robert-min** [comment]
# 아이디어 중간점검(28일)

## 구체적인 문제가 있는 경우

### 1. 보행 시 위험물 인지하는데 어려움 시각 장애인
- 문제
  - 지팡이와 같은 기존의 도구에 실시간으로 변화는 상황을 인지하기 어려움
  - 사회적 기반 시설(노란색 표시) 잘못되어 있는 곳이 많음
  - 교통 정보(지하철 방향, 버스 방향, 신호등), 보행 시 갑자기 오는 변수 등 대처하기 어려움
- 제안
  - 핸드폰 카메라를 활용하여 객체 탐지
    - 장점 : 바운딩 박스의 크기 등을 활용하여 접근 해오는 객체를 탐지 할 수 있음
    - 단점 : 핸드폰 카메라가 비추는 정면만 바라볼 수 있음
  - 시각 뿐만 아니라 최대한 많은 정보를 전달(소리, 진동, 정전기 등)
    - 장애인 + 휴대폰이 서로 커뮤니케이션해서 정보 전달(LLM)
- 참고
  - 장애인 대상으로 한 아이디어는 이미 종류가 많기도 하고 뻔한 아이디어일 수 있음

### 2. 문화재 건축물 인식이 부족한 학생
- 문제
  - 현장에서 문화재 교육이 전반적으로 부실하다.
- 제안
  - 인공지능 미술 가이드 큐레이션
    - ving ai? : 정확하게 매칭되는 결과 제공

### 3. 미술을 더 역동적으로 보고싶은 사람
- 문제
  - QR로 제공하는 콘텐츠가 부족

## 일상에서 반복적인 일 찾아 서비스화 -> Funsumer
따로 정리된 부분은 없어 키워드로 작성
- 일기로 멜로디를 만들어서 콘텐츠
  - 특별한 일기 Ex. 출산 일기 ,육아 일기 등
- 일상에서 반복적인 일을 서비스화 필요
  - 우리 서비스로 사용자가 지속적인 서비스 이용을 바라면 안됨
  - 이미 일상에서 하고 있는 일을 우리가 서비스해야 지속적인 서비스 가능
  - ex) 레브잇, 휴대폰 텃밭

> 1. 문제 정의를 통한 아이디어, 2. 일상에서 반복적인 일을 찾아 서비스화 중 두가지를 고민해보고 29일 회의 때 추가적인 구체화 진행

**Comment by robert-min** [comment]
> **_키워드만 적어서 따로 정리X -> 아이디어 리서치로 한 부분은 해당 이슈 확인_**

<br>

# 아이디어 회의(29일)

## 구체적인 문제가 있는 경우

### 1. 보행 시 위험물 인지하는데 어려움 시각 장애인
- 문제
  - 지팡이와 같은 기존의 도구에 실시간으로 변화는 상황을 인지하기 어려움
  - 사회적 기반 시설(노란색 표시) 잘못되어 있는 곳이 많음
  - 교통 정보(지하철 방향, 버스 방향, 신호등), 보행 시 갑자기 오는 변수 등 대처하기 어려움
- 제안
  - 핸드폰 카메라를 활용하여 객체 탐지
    - 장점 : 바운딩 박스의 크기 등을 활용하여 접근 해오는 객체를 탐지 할 수 있음
    - 단점 : 핸드폰 카메라가 비추는 정면만 바라볼 수 있음
  - 시각 뿐만 아니라 최대한 많은 정보를 전달(소리, 진동, 정전기 등)
    - 장애인 + 휴대폰이 서로 커뮤니케이션해서 정보 전달(LLM)
- 참고
  - **장애인 대상으로 한 아이디어는 이미 종류가 많기도 하고 뻔한 아이디어일 수 있음**





### 3. (고민) 미술을 더 역동적으로 보고싶은 사람
- 문제
  - QR로 제공하는 콘텐츠가 부족
  - 중점적으로 봐야하는 부분
- 해결
	- 미술 작품 설명
	- 설명(Frompt)
	- 동적인 미술 관람을 역동적인 서비스(GPT)


문제 - 필요
- 기존 미술 관심 저하 (단순 사진, 요즘 사람들 글자를 읽지 않음)
- 미술의 관심을 필요

해결
- B2B

데이터
- 한국 데이터
- text -> image, text -> video
- API - bing vision ai
- 위키 = 정확한 정보(fromting) + 
- 작가의 생각이 포함?
- 리서치 
- 정보 + 인공지능 + 포인트(작가 의견 등) + 재미

예술작품 해설


### 부모 없으신 분 or 혼자 사는 자취생 (AI family)
- 문제
	- 넥타이
	- 면도
- 해결
	- AI 부모
	- 유대감 => 타겟팅
	- 본인의 얼굴로 부모 얼굴로 만들어서 => 홈패드(인사)
	- 캘린더 
- 기술
	- 음성, 이미지, 모션, 표정

정보 격차를 줄이는 SKT
- 키오스크

학부모 사업




### 4. 멀리 있는거 잘 보이게
- 문제
	- 잘안보이는거 보고싶다.
- 해결
	- 기술적으로 해결한다.



## 일상에서 반복적인 일 찾아 서비스화 -> Funsumer
따로 정리된 부분은 없어 키워드로 작성
- 일기로 멜로디를 만들어서 콘텐츠
  - 특별한 일기 Ex. 출산 일기 ,육아 일기 등
- 일상에서 반복적인 일을 서비스화 필요
  - 우리 서비스로 사용자가 지속적인 서비스 이용을 바라면 안됨
  - 이미 일상에서 하고 있는 일을 우리가 서비스해야 지속적인 서비스 가능
  - ex) 레브잇, 휴대폰 텃밭

> 1. 문제 정의를 통한 아이디어, 2. 일상에서 반복적인 일을 찾아 서비스화 중 두가지를 고민해보고 29일 회의 때 추가적인 구체화 진행

딱히 필요없지만 -> 생기면 쓰는거

지하철노선도
- 빠른 노선
길찾기
유튜브
노래
인스타그램
카카오톡
날씨 - 오늘

우산 쓰는 등 한 손으로 폰할 때
- 문제
	- 핸드폰 사이즈가 커지면서 어려움
- 해결
	- 텍스트 to 텍스트 : 자동완성
	- vision to 텍스트 : 입모양,

핸드폰 보면서 걸어 갈 때
- 문제
	- 위험한 물체 확인이 어려움
- 해결
	- vision to 알림 : 위험 상황을 알려줌


지하철 환승 정보
- 문제
	- 지하철 빠른 환승 정보를 매번 찾아야함
- 해결
	- GPS 기준으로 알림


일상적인 기록(운동)을 거부가 없이 올림
- 문제
	- 부담스러워서 올리기 어려움

시간 
컨셉 정보 
- 교통 정보 
- 루틴 - 권한 설정
- 루틴을 파악

UI 디자인


이미지 멀리 

자동차
렌트카 빌리는 사람


공통 자소서 - 공통된 문서
뺘대 자소서
- 활동 정보를 input으로 넣어서
- 초안 작성을 해주는
- 자소서 비교 

면접
- AI 인성
- 면접 예상 질문

대학
- 공모전, 대외정보

밀리의 서재

일기 콘텐츠


반려동물
- MBTI
- 먹을 수 있는 음식 못먹는 음식 - 간식 추천

게임 해설

홈캠
- 반려동물 행동 -> 이상징후 -> 아픈지
- 강아지 오줌 -> 오줌 탐지

요리선생
- 주방 선반에 핸드폰 
- 요리하는 상황을 보고
- 다음 순서를 설명
- 게임적인 요소 => 게임적인 요소

운동
- 모션인식
- 재활


강의자료 - 강의 => 굿노트
- 강의 내용 기준 - 강의자료 특정 페이지 검색

곤충 종류 
- 곤충 도감
- 곤충 콘텐츠
- 우리 동네 곤충


미리보기
- 인생 미리보기
- 내 삶 (30년 후 내 생활)



멀티버스
- 10년? 

2023년
- VLM
	- detection
	- segment
	- pattern 찾기 퀴즈 
- SuperNova




그림
- 내가 전에 그린 그림
- 그림 스크래치 
- 페인팅

카페
- 공부
- 이야기

생각을 깊게 할 수 있게 도와주는 
- 질문을 계속
- 철학(생각, 반성, 기준을 정해서 이야기)
- 아이 심리 
- 정체성을 찾아가는 과정, 기준


30분 이상 영상 보기 어려움
- 유튜브 30분 영상에 익숙
- 집중력이 부족해짐
- 도파민 중독

중요한 키워드에 대한 질문 - 마인드 맵

콘텐츠 생성
- AI 이미지
- AI 목소리


스트레스
- 테니스
	- 몸을 움직이여야
- Fake Review detection
- 수집
	- 레고

- 업
	- 뱃지


공연 콘텐츠 - 생산자
- 교차 편집 + 뮤직비디오
- SKT : 야구 하이라이트 자동생성


국토 대장정

자전거
- 클리닝 서비스

### 잡이스
가구
- 설명서 -> 내상황 -> 어떻게 해야할까?
- 가구 조립 순서대로 번호가 표시 
- step
- 대화 - 커뮤니케이션

요리
- 


비주얼 사전
- 찍으면 확실한 정보 제공

피부에 아픈 부위 알려주면 -> 정보 제공

라바 - Multimodal => 의료 사진에 대한 정보 제공
